### ISSUE TITLE
Quitar idioma de AppLayout y meterlo en settings

### ISSUE THREAD

**Issue by gabrielurs** [JosepRoldan/DAW2324_S6#2]
Podríamos, en lugar de hacer que el idioma se muestre en todos lados, solo hacer que se muestre en 'Settings' y que, al cambiar de idioma, se cambie automáticamente toda la aplicación. Para hacer eso, se me ocurre inicializar una constante en 'App Layout' que se llame 'lang' y que, al entrar, verifique si el usuario ha escogido previamente un idioma (esto lo hacemos con localStorage); en caso de que no haya escogido ninguno, metemos 'EN' por defecto  @JosepRoldan

**Comment by rogeriesmontsia** [comment]
si o ponerlo abajo del todo en el sidebar... algun sitio que quede mas bonito
